import type { AppArchetype, BlueprintRole, BlueprintWorkflowKey, IndustryKey } from "./blueprint-types";

export const industries: Array<{ key: IndustryKey; label: string; category: string }> = [
  { key: "restaurant", label: "Restaurant", category: "hospitality" },
  { key: "cafe", label: "Cafe", category: "hospitality" },
  { key: "barbershop", label: "Barbershop", category: "local-service" },
  { key: "beauty-salon", label: "Beauty Salon", category: "wellness" },
  { key: "dental-clinic", label: "Dental Clinic", category: "health" },
  { key: "private-clinic", label: "Private Clinic", category: "health" },
  { key: "gym", label: "Gym", category: "fitness" },
  { key: "personal-trainer", label: "Personal Trainer", category: "fitness" },
  { key: "mechanic", label: "Mechanic", category: "automotive" },
  { key: "car-detailing", label: "Car Detailing", category: "automotive" },
  { key: "construction", label: "Construction", category: "trades" },
  { key: "electrician", label: "Electrician", category: "trades" },
  { key: "plumber", label: "Plumber", category: "trades" },
  { key: "cleaning-company", label: "Cleaning Company", category: "local-service" },
  { key: "real-estate", label: "Real Estate", category: "property" },
  { key: "hotel", label: "Hotel", category: "hospitality" },
  { key: "event-agency", label: "Event Agency", category: "events" },
  { key: "photographer", label: "Photographer", category: "creative" },
  { key: "ecommerce-fashion", label: "Ecommerce Fashion", category: "commerce" },
  { key: "ecommerce-electronics", label: "Ecommerce Electronics", category: "commerce" },
  { key: "ecommerce-furniture", label: "Ecommerce Furniture", category: "commerce" },
  { key: "online-course", label: "Online Course", category: "education" },
  { key: "coaching", label: "Coaching", category: "education" },
  { key: "law-firm", label: "Law Firm", category: "professional" },
  { key: "accounting", label: "Accounting", category: "professional" },
  { key: "childcare", label: "Childcare", category: "education" },
  { key: "school", label: "School", category: "education" },
  { key: "nonprofit", label: "Nonprofit", category: "community" },
  { key: "mosque-community", label: "Mosque Community", category: "community" },
  { key: "coworking", label: "Coworking", category: "workspace" },
  { key: "SaaS-dashboard", label: "SaaS Dashboard", category: "software" },
  { key: "AI-agency", label: "AI Agency", category: "software" },
  { key: "logistics", label: "Logistics", category: "operations" },
  { key: "delivery", label: "Delivery", category: "operations" },
  { key: "marketplace", label: "Marketplace", category: "commerce" },
  { key: "repair-service", label: "Repair Service", category: "local-service" },
  { key: "pet-care", label: "Pet Care", category: "wellness" },
  { key: "travel-agency", label: "Travel Agency", category: "hospitality" },
  { key: "wedding-service", label: "Wedding Service", category: "events" },
  { key: "portfolio-studio", label: "Portfolio Studio", category: "creative" }
];

export const appArchetypes: Record<AppArchetype, { label: string; description: string }> = {
  "booking-first": { label: "Booking First", description: "A conversion path centered on selecting a service, time, and confirmation." },
  "commerce-store": { label: "Commerce Store", description: "Product browsing, cart, checkout, and order confirmation." },
  "marketplace-grid": { label: "Marketplace Grid", description: "Search, filters, item cards, favorites, and provider/vendor actions." },
  "dashboard-first": { label: "Dashboard First", description: "Product or operational dashboard as the primary first screen." },
  "community-portal": { label: "Community Portal", description: "Member feed, events, announcements, profiles, and admin publishing." },
  "service-portal": { label: "Service Portal", description: "Services, quote request, jobs, status, and contact workflow." },
  "content-portfolio": { label: "Content Portfolio", description: "Cinematic work, case studies, galleries, and inquiry flows." },
  "course-platform": { label: "Course Platform", description: "Courses, enrollment, student dashboard, lesson preview, and progress." },
  "restaurant-experience": { label: "Restaurant Experience", description: "Menu, reservations, story, gallery, and opening hours." },
  "admin-command-center": { label: "Admin Command Center", description: "Dense control-room UI with CRUD, analytics, and role workflows." },
  "map-first-finder": { label: "Map First Finder", description: "Location-aware discovery with filters, cards, and saved places." },
  "step-wizard": { label: "Step Wizard", description: "Guided multi-step funnel for quotes, onboarding, or setup." },
  "mobile-app-interface": { label: "Mobile App Interface", description: "App-like navigation, compact surfaces, gestures, and bottom actions." },
  "membership-platform": { label: "Membership Platform", description: "Plans, member login, rewards, events, and gated content." },
  "donation-platform": { label: "Donation Platform", description: "Campaign storytelling, donation, volunteer forms, and updates." },
  "lead-gen-funnel": { label: "Lead Gen Funnel", description: "Trust-first marketing flow with quote/contact conversion." }
};

export const pageTypes = [
  "home",
  "booking",
  "menu",
  "shop",
  "products",
  "cart",
  "checkout",
  "dashboard",
  "admin",
  "marketplace",
  "listings",
  "details",
  "services",
  "pricing",
  "portfolio",
  "gallery",
  "case-studies",
  "events",
  "community",
  "members",
  "courses",
  "lessons",
  "profile",
  "contact",
  "about",
  "map",
  "donate",
  "quote",
  "schedule",
  "support"
] as const;

export const roles: BlueprintRole[] = ["visitor", "customer", "member", "student", "vendor", "staff", "editor", "admin", "owner", "driver", "agent", "provider"];

export const dataModelTemplates = {
  booking: { label: "Booking", fields: ["name:string", "email:email", "phone:phone", "date:date", "time:string", "status:enum"] },
  reservation: { label: "Reservation", fields: ["name:string", "email:email", "date:date", "time:string", "partySize:number", "occasion:string"] },
  product: { label: "Product", fields: ["name:string", "price:currency", "image:image", "category:string", "inStock:boolean"] },
  order: { label: "Order", fields: ["customer:string", "email:email", "total:currency", "status:enum", "items:relation"] },
  contactSubmission: { label: "Contact Submission", fields: ["name:string", "email:email", "message:string", "createdAt:datetime"] },
  review: { label: "Review", fields: ["author:string", "rating:number", "body:string", "createdAt:date"] },
  listing: { label: "Listing", fields: ["title:string", "price:currency", "location:string", "image:image", "status:enum"] },
  course: { label: "Course", fields: ["title:string", "level:enum", "duration:string", "price:currency", "instructor:string"] },
  lesson: { label: "Lesson", fields: ["title:string", "duration:string", "completed:boolean", "courseId:relation"] },
  member: { label: "Member", fields: ["name:string", "email:email", "role:enum", "joinedAt:date"] },
  event: { label: "Event", fields: ["title:string", "date:date", "location:string", "capacity:number"] },
  campaign: { label: "Campaign", fields: ["title:string", "goal:currency", "raised:currency", "deadline:date"] },
  vendor: { label: "Vendor", fields: ["name:string", "category:string", "rating:number", "verified:boolean"] },
  job: { label: "Job", fields: ["title:string", "status:enum", "scheduledAt:datetime", "assignee:string"] },
  quote: { label: "Quote", fields: ["name:string", "email:email", "scope:string", "budget:currency", "status:enum"] },
  article: { label: "Article", fields: ["title:string", "summary:string", "author:string", "publishedAt:date"] }
} as const;

export const workflowTemplates: Record<BlueprintWorkflowKey, { name: string; steps: string[]; actions: string[] }> = {
  booking: { name: "Create booking", steps: ["Select service", "Choose time", "Enter details", "Confirm"], actions: ["createBooking", "cancelBooking"] },
  reservation: { name: "Create reservation", steps: ["Pick date", "Choose party size", "Add occasion", "Confirm"], actions: ["createBooking", "cancelBooking"] },
  checkout: { name: "Checkout", steps: ["Add item", "Review cart", "Enter payment demo", "Confirm order"], actions: ["addToCart", "createOrder", "checkoutDemoPayment"] },
  contact: { name: "Contact form", steps: ["Enter message", "Validate details", "Store submission", "Show success"], actions: ["submitContactForm"] },
  leadCapture: { name: "Lead capture", steps: ["Qualify need", "Collect contact", "Assign status", "Confirm"], actions: ["submitContactForm", "createAdminItem"] },
  memberLogin: { name: "Member login", steps: ["Enter demo email", "Create session", "Load profile"], actions: ["loginDemoUser", "registerDemoUser"] },
  profileUpdate: { name: "Update profile", steps: ["Open profile", "Edit fields", "Persist profile"], actions: ["updateProfile"] },
  review: { name: "Create review", steps: ["Select rating", "Write note", "Publish locally"], actions: ["createReview"] },
  favorite: { name: "Favorite item", steps: ["Select item", "Persist favorite", "Update count"], actions: ["addFavorite"] },
  reward: { name: "Redeem reward", steps: ["Pick reward", "Validate points", "Confirm redemption"], actions: ["redeemReward"] },
  adminCrud: { name: "Admin CRUD", steps: ["Create item", "Update item", "Delete item"], actions: ["createAdminItem", "updateAdminItem", "deleteAdminItem"] },
  filterBrowse: { name: "Filter browse", steps: ["Select filters", "Apply results", "Save preference"], actions: ["addFavorite"] },
  quoteRequest: { name: "Quote request", steps: ["Describe project", "Set budget", "Submit quote"], actions: ["submitContactForm", "createAdminItem"] },
  courseEnrollment: { name: "Course enrollment", steps: ["Choose course", "Create account", "Enroll", "Open dashboard"], actions: ["registerDemoUser", "createOrder"] },
  donation: { name: "Donation", steps: ["Choose campaign", "Set amount", "Confirm demo payment"], actions: ["checkoutDemoPayment", "createOrder"] },
  vendorOnboarding: { name: "Vendor onboarding", steps: ["Enter vendor details", "Upload profile", "Submit for review"], actions: ["registerDemoUser", "createAdminItem"] }
};

export const visualDNAPresets = {
  "split-screen editorial": { density: "cinematic", colorMode: "mixed", motion: "slow parallax panels" },
  "immersive full-screen scroll": { density: "cinematic", colorMode: "dark", motion: "scroll-linked reveal masks" },
  "dashboard-first": { density: "dense", colorMode: "dark", motion: "live metric pulses" },
  "marketplace grid": { density: "balanced", colorMode: "light", motion: "filter morphs and card lift" },
  "luxury brochure": { density: "airy", colorMode: "mixed", motion: "soft editorial fades" },
  "booking-first funnel": { density: "balanced", colorMode: "mixed", motion: "step progress rail" },
  "map-first service finder": { density: "dense", colorMode: "light", motion: "map pin pulse" },
  "product-commerce grid": { density: "balanced", colorMode: "light", motion: "cart drawer slide" },
  "cinematic portfolio": { density: "cinematic", colorMode: "dark", motion: "gallery wipe and hover reveal" },
  "mobile-app style interface": { density: "dense", colorMode: "mixed", motion: "bottom sheet transitions" },
  "community feed": { density: "balanced", colorMode: "light", motion: "feed insert animation" },
  "command-center admin": { density: "dense", colorMode: "dark", motion: "terminal sweep and status glow" },
  "step-by-step wizard": { density: "balanced", colorMode: "light", motion: "wizard step morph" },
  "timeline storytelling": { density: "airy", colorMode: "mixed", motion: "vertical timeline reveal" },
  "modular magazine": { density: "balanced", colorMode: "mixed", motion: "asymmetric card choreography" },
  "glassmorphism control room": { density: "dense", colorMode: "dark", motion: "glass reflection drift" },
  "dark premium conversion": { density: "cinematic", colorMode: "dark", motion: "spotlight conversion pulse" },
  "soft neumorphism service portal": { density: "balanced", colorMode: "light", motion: "soft press states" },
  "playful youth app": { density: "balanced", colorMode: "light", motion: "springy micro interactions" },
  "high-trust medical layout": { density: "airy", colorMode: "light", motion: "calm progress fade" }
} as const;

export const interactionPatterns = {
  openBookingModal: { event: "click", demoBackendAction: "createBooking" },
  submitBooking: { event: "submit", demoBackendAction: "createBooking" },
  cancelBooking: { event: "click", demoBackendAction: "cancelBooking" },
  openCart: { event: "click", demoBackendAction: "addToCart" },
  addToCart: { event: "click", demoBackendAction: "addToCart" },
  checkout: { event: "submit", demoBackendAction: "checkoutDemoPayment" },
  submitContact: { event: "submit", demoBackendAction: "submitContactForm" },
  loginDemoUser: { event: "submit", demoBackendAction: "loginDemoUser" },
  registerDemoUser: { event: "submit", demoBackendAction: "registerDemoUser" },
  updateProfile: { event: "submit", demoBackendAction: "updateProfile" },
  createReview: { event: "submit", demoBackendAction: "createReview" },
  addFavorite: { event: "click", demoBackendAction: "addFavorite" },
  redeemReward: { event: "click", demoBackendAction: "redeemReward" },
  createAdminItem: { event: "click", demoBackendAction: "createAdminItem" },
  updateAdminItem: { event: "click", demoBackendAction: "updateAdminItem" },
  deleteAdminItem: { event: "click", demoBackendAction: "deleteAdminItem" },
  filterItems: { event: "change", demoBackendAction: "addFavorite" },
  switchPage: { event: "click", demoBackendAction: "updateProfile" }
} as const;

export const featureModules = {
  booking: { label: "Booking Flow", dataModels: ["booking"], workflows: ["booking"], interactions: ["openBookingModal", "submitBooking"] },
  reservations: { label: "Reservation Flow", dataModels: ["reservation"], workflows: ["reservation"], interactions: ["openBookingModal", "submitBooking"] },
  cart: { label: "Cart", dataModels: ["product", "order"], workflows: ["checkout"], interactions: ["openCart", "addToCart", "checkout"] },
  checkout: { label: "Checkout", dataModels: ["order"], workflows: ["checkout"], interactions: ["checkout"] },
  contact: { label: "Contact Form", dataModels: ["contactSubmission"], workflows: ["contact"], interactions: ["submitContact"] },
  reviews: { label: "Reviews", dataModels: ["review"], workflows: ["review"], interactions: ["createReview"] },
  favorites: { label: "Favorites", dataModels: ["listing"], workflows: ["favorite"], interactions: ["addFavorite"] },
  filters: { label: "Search Filters", dataModels: ["listing"], workflows: ["filterBrowse"], interactions: ["filterItems"] },
  quote: { label: "Quote Request", dataModels: ["quote"], workflows: ["quoteRequest"], interactions: ["submitContact"] },
  courseEnrollment: { label: "Course Enrollment", dataModels: ["course", "lesson"], workflows: ["courseEnrollment"], interactions: ["registerDemoUser", "checkout"] },
  memberPortal: { label: "Member Portal", dataModels: ["member"], workflows: ["memberLogin", "profileUpdate"], interactions: ["loginDemoUser", "updateProfile"] },
  rewards: { label: "Rewards", dataModels: ["member"], workflows: ["reward"], interactions: ["redeemReward"] },
  adminCrud: { label: "Admin CRUD", dataModels: ["job"], workflows: ["adminCrud"], interactions: ["createAdminItem", "updateAdminItem", "deleteAdminItem"] },
  events: { label: "Events", dataModels: ["event"], workflows: ["booking"], interactions: ["openBookingModal", "submitBooking"] },
  donations: { label: "Donations", dataModels: ["campaign", "order"], workflows: ["donation"], interactions: ["checkout"] },
  vendorOnboarding: { label: "Vendor Onboarding", dataModels: ["vendor"], workflows: ["vendorOnboarding"], interactions: ["registerDemoUser", "createAdminItem"] },
  listings: { label: "Listings", dataModels: ["listing"], workflows: ["filterBrowse"], interactions: ["filterItems", "addFavorite"] },
  contentPublishing: { label: "Content Publishing", dataModels: ["article"], workflows: ["adminCrud"], interactions: ["createAdminItem", "updateAdminItem"] },
  schedule: { label: "Schedule", dataModels: ["event"], workflows: ["booking"], interactions: ["openBookingModal", "submitBooking"] },
  dashboard: { label: "Dashboard", dataModels: ["job", "member"], workflows: ["adminCrud"], interactions: ["createAdminItem", "updateAdminItem"] }
} as const;
